### PR TITLE
Write to temp outfile until success, fixes #899

### LINKED ISSUE #899: Browserify should not create empty output files on error
When an error occurs, Browserify 5.11.2 creates an empty output file.  This should not happen, as it messes up `make`-based workflows.

```
$ cat >foo.js <<EOF
var quux = require('quux');
EOF

$ browserify foo.js -o bar.js
Error: Cannot find module 'quux' from '/private/tmp/foo'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:50:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:119:43)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:128:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)

$ ls -l | grep bar.js
-rw-r--r--  1 mietek  wheel   0 13 Sep 14:53 bar.js
```

### PR DESCRIPTION
**Pull request by natevw**
Write browserify command output to a temporary file, overwriting the target file atomically upon success (and simply cleaning up the tempfile on error).

This has two benefits:

* user won't be left with an empty file if compilation fails (which can break toolchains that rely on destination files/timestamps to indicate build status, Make or django-pipeline for just two examples) i.e. fixes #899 
* output file can never end up in a half-written state during even a successful compilation

### CODE REVIEW

**Comment by substack** [comment]
This patch looks good to me. Do you think this change should be a major or minor version bump?

**Comment by natevw** [comment]
@substack Hmmm, that's a good question. Given that this behavior wasn't documented [afaik?] and wasn't usually useful [imo], I'd call it a bug fix. But technically it does change the external behavior of the CLI tool, and therefore could conceivably break a build process that relies on the "empty file" behavior.

**Comment by natevw** [comment]
@feross @substack Any chance this could still get snuck into the major bump to 14?

**Comment by feross** [comment]
I'm fine considering this a patch or minor version, and doing a release. But would like confirmation from substack that he agrees.

**Comment by substack** [comment]
a minor version seems ok

**Comment by feross** [comment]
I actually don't have the time to do a release right now, sorry. Another maintainer want to take this?

**Comment by substack** [comment]
Thanks everyone. This feature has landed in 14.1.0.

**Comment by ljharb** [comment]
The module-deps upgrade is a breaking change; node 0.8 doesn't have setImmediate.

**Comment by substack** [comment]
This was fixed in 14.1.1 by using `process.nextTick()`. Thanks for catching this @ljarb.

**Comment by ljharb** [comment]
woot, thanks! 🎉

**Comment by benwiley4000** [comment]
Looks like #1746 is related to this one. Any ideas why?

**Comment by natevw** [comment]
@benwiley4000 I do not know why this would cause your issue, though I can't claim to fully understand your setup either. (Hopefully there's no internal code that tries to open the [eventual] output file for reading before it is finished being generated?)

**Comment by benwiley4000** [comment]
@natevw yeah, I'm not sure why either - I just know that when I was testing, I was able to reliably pinpoint the bug's origin with a before/after.

If you're curious about a repro, try running `npm run build` on this repo: https://github.com/benwiley4000/gif-frames

It should work find as-is, but if you change the name of the `bundled` field in package.json to `browser` it should fail (keep in mind that when browserify consumes a module it looks for the `browser` field so this could be related somehow).

**Pull request merged**
