### PR TITLE
Fix usage of deprecated Buffer API

### PR DESCRIPTION
**Pull request by seishun**
```
(node:23274) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```

See #1616. Only tests were affected.

Once Node.js 0.12 reaches EOL (January 1 2017), or whenever you feel comfortable with dropping 0.12 support, you can safely remove the "safe-buffer" dependency and the `require`s.

### CODE REVIEW

**Comment by mourner** [comment]
@substack any chance of merging this harmless PR? Those Node 7 warnings are pretty annoying.

**Comment by substack** [comment]
This patch updates tests. Why?

**Comment by substack** [comment]
I don't like this.

**Comment by seishun** [comment]
You don't like this because it updates tests?

>This patch ONLY updates tests, which I also don't understand.

"Only tests were affected." https://github.com/substack/node-browserify/pull/1647#issue-187509519

**Pull request closed without merging**
