### PR TITLE
fix npm links to avoid redirects and warnings

### PR DESCRIPTION
**Pull request by stevemao**
npm is now https://www.npmjs.com

### CODE REVIEW

**Comment by feross** [comment]
Could you resubmit this PR without all the random whitespace changes? Also remove `.gitattributes`.

**Comment by stevemao** [comment]
any reason for this? my editor auto removed all these whitespaces. This change makes other contributors easier to modify the file.

I realised there are inconsistent eol in `test/ignore.js` and my git always auto changes this. `.gitattributes` makes sure this won't happen again.

**Comment by feross** [comment]
Make separate PRs for those issues. Random whitespace changes makes it hard to see what actually changed, and make `git blame` useless.

**Comment by stevemao** [comment]
Done. Thanks.

**Comment by feross** [comment]
Thanks! Merged.

Test failure is due to a breaking change in iojs 1.6.0 that I'm about to file a bug for.

**Pull request merged**
