### PR TITLE
Sanitize json modules

### PR DESCRIPTION
**Pull request by zertosh**
Not all valid JSON is valid JS. http://timelessrepo.com/json-isnt-a-javascript-subset

### CODE REVIEW

**Comment by terinjokes** [comment]
Is there any reason why we shouldn't just replace these four characters?

**Comment by zertosh** [comment]
@terinjokes Modularize everything! But sure. I could just inline the regexp if you want.

**Comment by terinjokes** [comment]
Sorry, the module name was throwing me off. :~)

**Comment by zertosh** [comment]
@terinjokes Get this one out too?

**Pull request merged**
