### PR TITLE
fix eol

### PR DESCRIPTION
**Pull request by stevemao**
Set the default behavior, in case people do not have core.autocrlf set.

### CODE REVIEW

**Comment by substack** [comment]
I don't know what that is or why every line of test/ignore.js was updated:

```
 .gitattributes |   1 +
 test/ignore.js | 144 ++++++++++++++++++++++++++++-----------------------------
```

**Comment by stevemao** [comment]
@substack this file contains different eol character and my git just auto update it. I have set default eol globally. This configure Git to properly handle line endings so that it doesn't annoy other developers.

https://help.github.com/articles/dealing-with-line-endings/

**Comment by stevemao** [comment]
@substack/node-browserify can someone explain what is wrong with this PR and why it is not merged? Thanks. @feross @substack

**Comment by stevemao** [comment]
Can someone explain what is wrong with this PR and why it is not merged? Thanks. @feross @substack @jed  @itay  @nullobject

**Pull request closed without merging**
