### PR TITLE
readme: document opts.transform

### PR DESCRIPTION
**Pull request by LinusU**

### CODE REVIEW

**Comment by zertosh** [comment]
Thanks @LinusU, but I think they're a little more than "transform functions", and "modules" should be singular. How about borrowing some the language from https://github.com/substack/node-browserify#btransformtr-opts?

**Comment by LinusU** [comment]
Yes I was struggling a bit with what to write. It seems redundant to document how they works in two places in the documentation...

Do you think that we could link to `b.transform(tr, opts)` or maybe create a new section documenting how the source transforms works, and then linking to that?

**Comment by zertosh** [comment]
Yeah something short that links to https://github.com/substack/node-browserify#btransformtr-opts would be cool. The "Usage" section has a quick one-liner for "transform".

**Comment by jmm** [comment]
I've been thinking that eventually it might be a good idea to have a glossary kind of section for defining things like logical ideas and data structures that are referenced in multiple places. So you could have an entry for `transform` that's linked to from `opts.transform` (if that indeed gets documented) and `b.transform()`. That's what I was alluding to in #1226 when I talked about documenting `file object` and `entry file` at some point. And it'll be the same deal as here if `opts.require` gets documented as discussed in #1220.

**Comment by mattfysh** [comment]
Is there a reason for this PR not being merged? we're hoping to use this API but not too comfortable with its undocumented state

**Comment by LinusU** [comment]
Thanks!

**Pull request merged**
