### PR TITLE
use same instance on symlinked modules

### LINKED ISSUE #1063: Modules are executed multiple times when using symlinks in node_modules
I have following symlink in my project

    ln -sf .. node_modules/app

and I require modules like this

```js
var config = require("app/config");
```
etc.

but in this case the config module is executed multiple times when it is required from different js files.

Here's smallest possible example reproducing this https://github.com/epeli/browserify-bug

This bug was introduced in the 8.0.0 release.

--

The symlink idea is from the browserify handbook https://github.com/substack/browserify-handbook#symlink

### PR DESCRIPTION
**Pull request by chrisirhc**
Handle required packages by their real path.

Resolves #1063

Again, this is a request for further comment.

This isn't using a cache which might be faster (or not, since resolve might only be called for new packages encountered).

### CODE REVIEW

**Comment by chrisirhc** [comment]
Updated PR. Tests now pass.

**Comment by substack** [comment]
Aside from the sync issue, this looks good.

**Comment by substack** [comment]
I added some tests for the case in #831 and everything works. Published in 10.2.5/10.2.6. Thanks for the patch!

**Comment by marcello3d** [comment]
This update is breaking our build. :-( 

Problem: 

1. We have two modules, `app` and `shared`
2. `shared` is symlinked into `app`
3. Both `app` and `shared` use a module `foo`, which is installed in `app/node_modules/foo` (but not `shared/node_modules`)
4. Now `shared` can't find `foo`

**Pull request merged**
